### PR TITLE
Sanitizer build

### PR DESCRIPTION
**Pull request by jmgorius**
Add support for sanitizer builds and update the CI configuration accordingly. Simplify the CI configuration slightly by centralizing configuration options in the top-level environment and by using multi-line `run` commands.

### CODE REVIEW

**Comment by jmgorius** [comment]
There seems to be undefined references to sanitizer functions. I will try to figure out why this happens.

**Comment by jmgorius** [comment]
The build is now fixed. The sanitizers have detected a memory leak in the simulator.

**Comment by jmgorius** [comment]
After some more investigation, it turns out the memory is lost in the call to `engine->invoke` here
```c++
int Engine::simulate(int n) {
  assert(engine && "engine not found");
  assert(state && "state not found");

  SmallVector<void *, 1> arg({&state});
  // initialize simulation state
  auto invocationResult = engine->invoke("llhd_init", arg);
  if (invocationResult) {
    llvm::errs() << "Failed invocation of llhd_init: " << invocationResult;
    return -1;
  }
  // ...
}

**Comment by rodonisi** [comment]
Thanks a lot for the PR and looking into it, that's awesome!
That specific `ExecutionEngine` invocation includes `malloc`'ing memory regions for the signal's values. Those pointers are then stored in the `State` struct but never `free`'d explicitly. What would you suggest to be a good way to handle this? Do you think having a `State` destructor that loops over signals and explicitly calls `free` for each of them would be fine?

**Comment by jmgorius** [comment]
Yes, I think it would be a good solution. Right now the leaks are small but I would expect real-world examples to have way more allocations, so taking care of it would not hurt.

If you want to stay C-friendly you could also have a `free_state(State *state)` function that takes care of the deallocation.

**Comment by rodonisi** [comment]
It works now!
I don't think there's a need for a C-friendly function for the deallocation, as the state lives and is mainly interacted with in simulator itself

**Comment by jmgorius** [comment]
> I don't think there's a need for a C-friendly function for the deallocation, as the state lives and is mainly interacted with in simulator itself

True. Nice to see that this was the only detected issue!

**Comment by rodonisi** [comment]
Otherwise there's just a missing newline in the new cmake module, I'm not sure how important that is though

**Comment by jmgorius** [comment]
Fixed it.

**Comment by rodonisi** [comment]
Allright, thanks a lot :)

**Pull request merged**
